// AUTO-GENERATED by scripts/parse-cards.mjs — do not edit by hand.
// Run `node scripts/parse-cards.mjs` to regenerate from Game Assets/*.html.

import type { ContractCard } from "./types";

export const CONTRACT_CARDS: ContractCard[] = [
  {
    "id": "five-points-hustle",
    "name": "Five Points Hustle",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Control Five Points and hold 2+ barrels of the most valuable liquor there (ties fail).",
    "artPath": "/Art/Jobs/Five Points Hustle.png"
  },
  {
    "id": "moonshine-express",
    "name": "Moonshine Express",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Have your Boss in a Moonshine Speakeasy with 4+ barrels of Moonshine.",
    "artPath": "/Art/Unload 2.png"
  },
  {
    "id": "the-crimson-coup",
    "name": "The Crimson Coup",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Control 3+ Districts in a Borough containing a Rival Safehouse.",
    "artPath": "/Art/Jobs/Crimson Coup.png"
  },
  {
    "id": "bloody-sunday",
    "name": "Bloody Sunday",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Have 8+ Runners in Districts adjacent to the same Rival Safehouse.",
    "artPath": "/Art/Jobs/Bloody Sunday.PNG"
  },
  {
    "id": "empire-state",
    "name": "Empire State",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold more Cash ($) than any other single Rival.",
    "artPath": "/Art/Jobs/Empire State.png"
  },
  {
    "id": "the-toll-booth-trap",
    "name": "The Toll Booth Trap",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Ensure at least 1 rival mob has no Boss in play.",
    "artPath": "/Art/Jobs/Toll Booth Trap.png"
  },
  {
    "id": "the-milk-run",
    "name": "The Milk Run",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold at least 2 barrels of each Liquor type across Districts you Control.",
    "artPath": "/Art/Jobs/The Milk Run.png"
  },
  {
    "id": "rum-runner-s-regatta",
    "name": "Rum Runner's Regatta",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 4+ barrels of Rum in Dock Districts you Control.",
    "artPath": "/Art/Jobs/Rum Runners Regatta.png"
  },
  {
    "id": "stock-market-swindle",
    "name": "Stock Market Swindle",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 4+ barrels of the lowest-valued Liquor type (ties fail), in a District with a different Still type.",
    "artPath": "/Art/Jobs/Stock Market Swindle.png"
  },
  {
    "id": "high-roller",
    "name": "High Roller",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Have your Boss in The Tenderloin with at least $2,500 cash.",
    "artPath": "/Art/Jobs/High Roller.png"
  },
  {
    "id": "union-dues",
    "name": "Union Dues",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Have at least 8 Runners in Ghetto Districts.",
    "artPath": "/Art/Jobs/Union Dues.png"
  },
  {
    "id": "lexington-avenue-laundry",
    "name": "Lexington Avenue Laundry",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold $2,500+ Cash and have no markers on the Heat Track.",
    "artPath": "/Art/Jobs/Laundry.png"
  },
  {
    "id": "the-debt-collector",
    "name": "The Debt Collector",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 5+ barrels of Liquor in a Borough whose Deed is held by a rival.",
    "artPath": "/Art/Jobs/Debt Collector.png"
  },
  {
    "id": "the-insurance-job",
    "name": "The Insurance Job",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Control a Speakeasy matching the liquor type of a #12 Still you Control.",
    "artPath": "/Art/Jobs/Insurance Job.png"
  },
  {
    "id": "the-angel-s-share",
    "name": "The Angel's Share",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Your Boss must be in a Whisky Speakeasy holding 3+ barrels of Whisky.",
    "artPath": "/Art/Jobs/The Angels Share.png"
  },
  {
    "id": "frame-job",
    "name": "Frame Job",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Have 0 Influence on the Heat Track, while a single Rival has 2+.",
    "artPath": "/Art/Jobs/Frame Job.png"
  },
  {
    "id": "the-quiet-drop",
    "name": "The Quiet Drop",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 3+ barrels of Gin in a Staten Island Dock District.",
    "artPath": "/Art/Jobs/Quiet Drop.png"
  },
  {
    "id": "full-steam-ahead",
    "name": "Full Steam Ahead",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Control a District containing a Still of each type, with 3+ Runners in each.",
    "artPath": "/Art/Jobs/Full Steam.png"
  },
  {
    "id": "cross-town-switch",
    "name": "Cross-Town Switch",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 3+ barrels of Whisky in Queens and 3+ barrels of Gin in Manhattan.",
    "artPath": "/Art/Jobs/Switch.png"
  },
  {
    "id": "market-correction",
    "name": "Market Correction",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 5+ barrels of the highest-valued Liquor type (ties fail), in a single District.",
    "artPath": "/Art/Jobs/Market Correction.png"
  },
  {
    "id": "the-gin-pipeline",
    "name": "The Gin Pipeline",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Have Safehouses in Hunts Point and Brownsville, and hold 2+ Gin in each District.",
    "artPath": "/Art/Jobs/Gin Pipeline.png"
  },
  {
    "id": "cobble-hill-connection",
    "name": "Cobble Hill Connection",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control 2+ Districts in both Brooklyn & Queens.",
    "artPath": "/Art/Jobs/Cobble Hill.png"
  },
  {
    "id": "the-sullivan-scheme",
    "name": "The Sullivan Scheme",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control 3+ Speakeasies South of the East River (Brooklyn & Queens), and have $2,000+ Cash on hand.",
    "artPath": "/Art/Jobs/Scheme.png"
  },
  {
    "id": "the-empty-casket",
    "name": "The Empty Casket",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Hold a Borough Deed while you have fewer than 5 of your mobsters in that Borough.",
    "artPath": "/Art/Jobs/The Empty Casket.png"
  },
  {
    "id": "omert-s-shadow",
    "name": "Omertà's Shadow",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Have a Safehouse in every Borough that contains a rival Boss.",
    "artPath": "/Art/Jobs/Omerta.PNG"
  },
  {
    "id": "the-butcher-s-ledger",
    "name": "The Butcher's Ledger",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Have more Runners North of the East River (Manhattan & The Bronx) than any rival (ties fail).",
    "artPath": "/Art/Jobs/Butchers Ledger.png"
  },
  {
    "id": "coney-island-heist",
    "name": "Coney Island Heist",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Have a Safehouse in Coney Island and hold 2+ barrels of each type there.",
    "artPath": "/Art/Jobs/Coney Island.png"
  },
  {
    "id": "fortress-staten",
    "name": "Fortress Staten",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control all Staten Island Districts, and have a Safehouse in both Docks.",
    "artPath": "/Art/Jobs/Fortress Staten.png"
  },
  {
    "id": "the-night-mayor",
    "name": "The Night Mayor",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control more Speakeasies than any single rival (ties fail).",
    "artPath": "/Art/Jobs/Night Mayor.png"
  },
  {
    "id": "ghosts-in-the-shadows",
    "name": "Ghosts in the Shadows",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Have at least 2 mobsters in every Borough.",
    "artPath": "/Art/Jobs/Ghosts.png"
  },
  {
    "id": "high-spirits",
    "name": "High Spirits",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control 2+ High Society Districts and 2+ Whisky Stills.",
    "artPath": "/Art/Jobs/High Spirits.png"
  },
  {
    "id": "hell-s-highway",
    "name": "Hell's Highway",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control a continuous chain of Districts (land or bridge) from East Harlem to Flushing (inclusive).",
    "artPath": "/Art/Jobs/Hells Highway.png"
  },
  {
    "id": "the-big-squeeze",
    "name": "The Big Squeeze",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Hold the Borough Deed for the Borough containing the most Liquor barrels (ties fail).",
    "artPath": "/Art/Jobs/Big Squeeze.png"
  },
  {
    "id": "the-dutchman-s-deal",
    "name": "The Dutchman's Deal",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Hold more Gin barrels than any single rival (ties fail).",
    "artPath": "/Art/Jobs/Dutchman.png"
  },
  {
    "id": "tenement-army",
    "name": "Tenement Army",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control 3+ Ghetto Districts.",
    "artPath": "/Art/Jobs/Tenament Army.png"
  },
  {
    "id": "bathtub-chemistry",
    "name": "Bathtub Chemistry",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control 4+ Gin Stills.",
    "artPath": "/Art/Jobs/Bathtub Chemistry.png"
  },
  {
    "id": "cuban-prince",
    "name": "Cuban Prince",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control 2+ Dock Districts and hold 4+ Rum in each.",
    "artPath": "/Art/Jobs/Cuban Prince.png"
  },
  {
    "id": "gentleman-jimmy-s-shindig",
    "name": "Gentleman Jimmy's Shindig",
    "tier": "racket",
    "deadline": 2,
    "respect": 3,
    "take": 1500,
    "objective": "Control Morris Park with your Boss present, hold 3+ Rum there, and have $2,500+ Cash.",
    "artPath": "/Art/Jobs/Jimmy.png"
  },
  {
    "id": "cutting-the-product",
    "name": "Cutting the Product",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Hold 3+ barrels of Moonshine in a District you Control with a Whisky Still.",
    "artPath": "/Art/Jobs/Cutting.png"
  },
  {
    "id": "the-beachhead",
    "name": "The Beachhead",
    "tier": "gig",
    "deadline": 1,
    "respect": 1,
    "take": 500,
    "objective": "Have a Safehouse and 2+ Rum in the same District within a Borough whose Deed is held by a rival.",
    "artPath": "/Art/Jobs/Beachhead.png"
  },
  {
    "id": "harlem-shakedown",
    "name": "Harlem Shakedown",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control 5+ Districts in Manhattan.",
    "artPath": "/Art/Jobs/Beg.png"
  },
  {
    "id": "the-copper-heist",
    "name": "The Copper Heist",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control all three #7 Stills.",
    "artPath": "/Art/Jobs/Copper Heist.png"
  },
  {
    "id": "the-poison-panic",
    "name": "The Poison Panic",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control at least 1 Still of each type and hold 5+ barrels of matching liquor in each.",
    "artPath": "/Art/Jobs/Poison Panic.png"
  },
  {
    "id": "the-last-call",
    "name": "The Last Call",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control 4+ Speakeasies in Manhattan and the Bronx.",
    "artPath": "/Art/Jobs/Last Call.png"
  },
  {
    "id": "the-informant-s-secret",
    "name": "The Informant's Secret",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Hold more barrels of the highest-valued Liquor type than any rival (ties on value or quantity fail).",
    "artPath": "/Art/Jobs/Informant.png"
  },
  {
    "id": "rum-wars",
    "name": "Rum Wars",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control Dock Districts in 3+ Boroughs, and hold more Rum than all rivals combined.",
    "artPath": "/Art/Jobs/Rum Wars.png"
  },
  {
    "id": "south-side-embargo",
    "name": "South Side Embargo",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control 4+ Speakeasies on the South Side of the East River (Brooklyn & Queens).",
    "artPath": "/Art/Jobs/Embargo.png"
  },
  {
    "id": "the-big-sleep",
    "name": "The Big Sleep",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Surround a rival Boss so they cannot move without entering Hostile turf (if at a Dock, all other Docks must be Hostile).",
    "artPath": "/Art/Jobs/The Big Sleep.png"
  },
  {
    "id": "dock-domination",
    "name": "Dock Domination",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control at least 4 Dock Districts.",
    "artPath": "/Art/Jobs/Dock Domination.png"
  },
  {
    "id": "the-irish-goodbye",
    "name": "The Irish Goodbye",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Have more Runners in play than any rival (ties fail).",
    "artPath": "/Art/Jobs/Goodbye.png"
  },
  {
    "id": "black-hand-rising",
    "name": "Black Hand Rising",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control at least 1 District in every Borough.",
    "artPath": "/Art/Jobs/Black Hand.png"
  },
  {
    "id": "the-gatsby-run",
    "name": "The Gatsby Run",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Hold at least 4 barrels of each Liquor type in a single Borough.",
    "artPath": "/Art/Jobs/Gatsby.png"
  },
  {
    "id": "the-king-of-queens",
    "name": "The King of Queens",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control all 3 Speakeasies in Queens.",
    "artPath": "/Art/Jobs/King of Queens.png"
  },
  {
    "id": "the-grand-tour",
    "name": "The Grand Tour",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control a Speakeasy of each Domestic type (Moonshine, Gin, Whisky) plus at least 1 Dock.",
    "artPath": "/Art/Jobs/Grand Tour.png"
  },
  {
    "id": "the-old-guard",
    "name": "The Old Guard",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control 3+ High Society Districts.",
    "artPath": "/Art/Jobs/Old Guard.png"
  },
  {
    "id": "the-five-points-accord",
    "name": "The Five Points Accord",
    "tier": "score",
    "deadline": 3,
    "respect": 5,
    "take": 3000,
    "objective": "Control at least 1 Speakeasy in every Borough except Staten Island.",
    "artPath": "/Art/Jobs/Accord.png"
  }
];

export const CONTRACTS_BY_TIER = {
  gig: CONTRACT_CARDS.filter((c) => c.tier === "gig"),
  racket: CONTRACT_CARDS.filter((c) => c.tier === "racket"),
  score: CONTRACT_CARDS.filter((c) => c.tier === "score"),
};
