// One-shot parser: reads Game Assets HTMLs and emits src/game/cards.generated.ts
// Usage: node scripts/parse-cards.mjs
//
// Regex-based — the source HTML is hand-authored and very regular, so this is
// simpler than pulling in jsdom/cheerio. Re-run whenever the HTMLs change.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS = path.resolve(__dirname, "../../Game Assets");
const OUT = path.resolve(__dirname, "../src/game/cards.generated.ts");

function read(name) {
  return fs.readFileSync(path.join(ASSETS, name), "utf8");
}

function stripHtml(s) {
  return s
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

// ---- Contract cards ----
// Each card: <div class="card job-image-card"> ... <h2 class="mission-name">NAME</h2>
//   <span class="respect-badge" data-respect="N">N</span>
//   <div class="job-image-container" style="background-image: url('Art/...');"></div>
//   <div class="deadline-bar">DEADLINE: N DAY(S)</div>
//   <div class="Jobs-content">OBJECTIVE</div>
//   <div class="take-value">Take: $N</div>
// </div>

function parseContracts() {
  const html = read("Contract Cards v4.5.html");
  const cards = [];
  // Split on each job-image-card opener (cheap & cheerful)
  const blocks = html.split(/<div class="card job-image-card">/i).slice(1);
  for (const block of blocks) {
    const end = block.indexOf("</div>\n    </div>"); // outer card close — heuristic
    const slice = end === -1 ? block : block.slice(0, end + 40);

    const name = match(slice, /<h2 class="mission-name">([^<]+)<\/h2>/);
    const respect = parseInt(match(slice, /data-respect="(\d+)"/) ?? "0", 10);
    const art = match(slice, /background-image:\s*url\('([^']+)'\)/);
    const deadlineRaw = match(slice, /DEADLINE:\s*(\d+)\s*DAY/i);
    const deadline = deadlineRaw ? parseInt(deadlineRaw, 10) : null;
    const objective = stripHtml(match(slice, /<div class="Jobs-content">([\s\S]*?)<\/div>/) ?? "");
    const takeRaw = match(slice, /Take:\s*\$([\d,]+)/);
    const take = takeRaw ? parseInt(takeRaw.replace(/,/g, ""), 10) : null;

    if (!name) continue;
    const tier =
      respect === 1 ? "gig" : respect === 3 ? "racket" : respect === 5 ? "score" : null;
    if (!tier || !deadline || !take) {
      console.warn("Skipping malformed contract:", name, { respect, deadline, take });
      continue;
    }
    cards.push({
      id: slug(name),
      name,
      tier,
      deadline,
      respect,
      take,
      objective,
      artPath: art ? "/" + art : null,
    });
  }
  return cards;
}

function match(s, re) {
  const m = s.match(re);
  return m ? m[1] : null;
}

function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ---- Run ----
const contracts = parseContracts();
const byTier = contracts.reduce(
  (acc, c) => {
    acc[c.tier].push(c);
    return acc;
  },
  { gig: [], racket: [], score: [] }
);

console.log(`Parsed ${contracts.length} contracts: ${byTier.gig.length} gigs, ${byTier.racket.length} rackets, ${byTier.score.length} scores`);

const out = `// AUTO-GENERATED by scripts/parse-cards.mjs — do not edit by hand.
// Run \`node scripts/parse-cards.mjs\` to regenerate from Game Assets/*.html.

import type { ContractCard } from "./types";

export const CONTRACT_CARDS: ContractCard[] = ${JSON.stringify(contracts, null, 2)};

export const CONTRACTS_BY_TIER = {
  gig: CONTRACT_CARDS.filter((c) => c.tier === "gig"),
  racket: CONTRACT_CARDS.filter((c) => c.tier === "racket"),
  score: CONTRACT_CARDS.filter((c) => c.tier === "score"),
};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
